version: "3.7"
services:
  api:
    container_name: api
    build: ./api
    environment:
      PG_CONNECTION_STRING: postgres://admin:basic123@animes:5432/animes
    ports:
      - 2002:2002
    volumes:
      - ./api/src:/usr/app/api/src


  db:
    container_name: animes   
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: basic123
      POSTGRES_USER: admin
      POSTGRES_DB: animes
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432